
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "labelsmanager-controller.fullname" . }}
  labels:
    {{- include "labelsmanager-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - labels.rackbrains.io
  resources:
  - labels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - labels.rackbrains.io
  resources:
  - labels/status
  verbs:
  - get
  - patch
  - update

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "labelsmanager-controller.fullname" . }}
  labels:
    {{- include "labelsmanager-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "labelsmanager-controller.fullname" . }}
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: {{ include "labelsmanager-controller.fullname" . }}
